#!/usr/bin/env sh
#
# Rofi powered menu to prompt a password.
# Uses: rofi

cd "$( dirname "${BASH_SOURCE[0]}" )"
source "./common/definitions"

# print usage
prog="${0##*/}"
usage="${texts[usage]}: $prog [${texts[options]}]

    ${texts[prompt_usage]}
"

# parse options
handle_script_opts "$@"
rofiargs="${default_rofiargs} -format f "

#entry_accept="<span fallback='y'>${icons[yes]}</span>&#x0009;&#x2068;${texts[confirm]}&#x2069;"
#entry_cancel="<span fallback='y'>${icons[cancel]}</span>&#x0009;&#x2068;${texts[cancel]}&#x2069;"

#-mesg "${texts[fb_header]}" \
#-theme-str "@import \"./common/themes/vertical_menu.rasi\" ${default_themestr}" \
path=$( ${ROFI} ${rofiargs} -show filebrowser )
#warn "ret=$? pass=$password query=${query} ${texts[accept]} ${texts[cancel]} "

rofi_ret=$?

case ${rofi_ret} in
0)  # Entry chosen
    echo -e "${path}"
;;
1)  die 1 ""
;;
1[0-9]|2[0-8]) # run new instance on custom key chosen
	./${prog} ${args}
;;
*)  die ${rofi_ret} "${texts[error]:-"Error: "}${rofi_ret}"
;;
esac
