#!/usr/bin/env sh
#
# Rofi powered menu to confirm previous choise.
# Uses: rofi
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
source "./common/definitions"

# print usage
prog="${0##*/}"
nprog=${prog//-/_}
usage="${texts[usage]}: $prog [${texts[options]}]

    ${texts[confirm_usage]}
"

prompt_header="${texts[areyousure]}"
# parse options
while [ "$#" -ge 1 ]; do
    case "${1}" in
        -n|--name)
            prompt_header="${2}"
            shift
        ;;
    esac
    shift
done

handle_common_opts "$@"

entries+="$(write_menuentry "${texts[confirm]^}" " " "${icons[yes]}" "false" "true" "false" "false")"
entries+="$(write_menuentry "${texts[cancel]^}" " " "${icons[cancel]}" "false" "true" "false" "false")"

chosen=$(echo -en "${entries}" | ${ROFI} ${rofiargs} -mesg "${prompt_header^}" -theme-str '@import "./common/themes/confirm.rasi"' -dmenu -selected-row 1 -format i)

case "$chosen" in
    "0") exit 0 ;;
    *)   exit 1 ;;
esac
