#!/usr/bin/env sh
#
# Rofi powered menu to prompt a password.
# Uses: rofi
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog="${prog//-/_}"
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_common_opts "$@"
rofiargs="${default_rofiargs// -dmenu} -no-custom -format p "

header="${texts[header_file_picker]:-File picker}"
theme="./common/themes/vertical_menu.rasi"

FB_START_DIR="${@:-"${HOME}"}" # starting directory
FB_START_DIR="$(readlink -e "${FB_START_DIR}")"

send_notification "start from: ${FB_START_DIR}"

LS="/bin/ls -A1 --group-directories-first --color=never"
#places="$(${GREP} -IEe \/dev\/ /proc/mounts | cut -d' ' -f 2 )
places="$(${LS} "${FB_START_DIR}")"

#warn ${places}

get_icon() {
    local file=${@?${texts[missingarg]:-Missing argument} file}
    [ -d "${file}" ] && echo "folder" || echo "$file"
}

#i=0
while IFS=$NF read -r name ; do 
    #name="${line##*\/}"
    #path="${line%\/*}"
    path="${FB_START_DIR}/${name}"
    entries+="$(write_menuentry "${name}" "false" "$(get_icon ${path})" "true")"
    #actions+=( "./${prog} ${args} ${line//\//\\/}" )
    #error_msgs+=( "" )
    #warn "${actions[$i]}"
    #i=$((i+1))
done <<< "${places}"

#entries+="$(write_menuentry "${texts[select]:-Select}" "false" )"
#actions+=( "echo ${f}" )

handle_rofi

if ${force_dmenu}; then
	case ${rofi_ret} in
		0)  # selected
			wl-copy -p "${chosen_row}" 2>/dev/null
			send_notification "${texts[selected]:-selected}: ${chosen_row}"
		;;
		1)  # Cancelled by user
    		die 0 "${texts[canceled]:-"Cancelled..."}"
		;;
	esac
	"./${prog} ${args} ${FB_START_DIR}/${chosen_row}"
else
	case ${ROFI_RETV} in
	    1)  # copy
			wl-copy -p "${@}" 2>/dev/null
			send_notification "${texts[selected]:-selected}: ${@}"
	    ;;
	esac
	export ROFI_DATA="${@}"
fi
