#!/usr/bin/env sh
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
SWAYMSG="swaymsg"
SWAYBG="swaybg"
MPVPAPER='mpvpaper -f -p -o profile=mpvpaper'
JQ="/usr/bin/jq --unbuffered -r"
RDEPS+="${SWAYMSG},${SWAYBG},${MPVPAPER},${JQ},"

WPSRCDIR="~/Wallpapers"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options

handle_common_opts "$@"

rofiargs+=" -dmenu"
# default_themestr+="element-text { tab-stops: [8em, 9em, 10.1em]; } "
theme="./common/themes/vertical_menu.rasi"
header="${texts[header_sway_display]}"

declare -A switch power
switch=( 
    [true]=off [false]=on
    [enabled]=off [disabled]=on
)
power=(
    [enabled]=on [disabled]=off
)

default_transform(){
    local transform="${1?${texts[missingarg]:-"Missing argument transform"}}"
    [[ "${transform}" == "normal" ]] && echo true || echo false
}

mklink() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    IFS='|' read -d '' -r bgname bginfill bgcolor null <<< "${last_bg[${index}]}|"
    local display="${displays[index]}"
    #send_notification "name: ${bgname}, infill: ${bginfill}, color: ${bgcolor}"
    ${FIND} "${HOME}/.local/state" -type l -name "lastbg_${display#* }_*" -exec rm {} \;
    ln -snf "${bgname}" "${HOME}/.local/state/lastbg_${display#* }_${bginfill}_${bgcolor}"
    return $?
}

set_mode() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local enabled="false"
    entries="";
    IFS=$NF read -r -d '' -a modes <<< "$($JQ '.['${index}'] | .modes[] |  [.width, "x", .height, "@", .refresh] | join("")' <<< ${outputs})"
    for i in "${!modes[@]}"; do
        enabled=$([[ "${curr_modes[index]}" == "${modes[i]}" ]] && echo true || echo false )
        entries+="$(write_menuentry "${modes[i]:0:-3}.${modes[i]: -3}Hz" \
            "${SWAYMSG} output \"${display#* }\" mode \"${modes[$i]:0:-3}.${modes[$i]: -3}Hz\"" \
            "${icons[displaymode]}" "${enabled}" "false" "false" "false" \
            "${texts[cantset]} ${texts[display]} ${texts[displaymode]}" \
        )"
    done
    #header="${texts[header_sway_display_modes]:-"Availiable display modes"}"
    header="${texts[availiable]} ${texts[options]} ${texts[modes]}"

    theme="./common/themes/vertical_menu.rasi"
    handle_rofi
    return $?
}

set_position() {
    local rofi_ret pos
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local curr_pos="${positions[index]%%,*}, ${positions[index]##*, }"
    pos=$(./urd-prompt -n "${texts[display_position]:-"Enter display position coordinates"} (${curr_pos})" -p "${texts[displayposition]^}" )
    rofi_ret="$?"
    test ${rofi_ret} -eq 0 && run_menuentry_action "${SWAYMSG} output \"${display#* }\" position \"${pos}\"" "${texts[cantset]} ${texts[display]} ${texts[position]}"
    return $?
}

set_scale() {
    local rofi_ret scale
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local curr_scale="${scales[index]}"
    scale="$(./urd-prompt -n "${texts[display_scale]:-"Enter display scale multiplier"}" -p "${texts[displayscale]^}" )"
    rofi_ret="$?"
    test ${rofi_ret} -eq 0 && run_menuentry_action "${SWAYMSG} output \"${display#* }\" scale \"${scale}\"" "${texts[cantset]} ${texts[display]} ${texts[scale]}"
    return $?
}

set_transform() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local curr_trans="${transforms[index]}"
    declare -a trans
    entries=""; 
    trans=("normal" "flipped" "90" "180" "270" "flipped-90" "flipped-180" "flipped-270")
    for i in "${!trans[@]}"; do
        enabled=$([[ "${curr_trans}" == "${trans[i]}" ]] && echo true || echo false )
        entries+="$(write_menuentry "${texts[displaytransform_${trans[$i]}]^}" \
            "${SWAYMSG} output \"${display#* }\" transform ${trans[i]}" \
            "${icons[displaytransform]}" "${enabled}" "true" "false" "false" \
            "${texts[cantset]} ${texts[display]} ${texts[transform]}" \
        )"
    done
    header="${texts[availiable]} ${texts[options]} ${texts[transform]}"
    theme="./common/themes/vertical_menu.rasi"

    handle_rofi
    return $?
}

set_hinting() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local curr_hint="${hintings[index]}"
    entries="";
    declare -a hints
    local hints=("rgb" "bgr" "vrgb" "vbgr" "none")
    for i in "${!hints[@]}"; do
        enabled=$([[ "${curr_hint}" == "${hints[i]}" ]] && echo true || echo false )
        entries+="$(write_menuentry "${texts[${hints[i]}]}" \
            "${SWAYMSG} output \"${display#* }\" subpixel ${hints[$i]}" \
            "${icons[displayhinting]}" "${enabled}" "true" "false" "false" \
            "${texts[cantset]} ${texts[display]} ${texts[hinting]}" \
        )"
    done
    header="${texts[availiable]} ${texts[hinting]}"
    theme="./common/themes/vertical_menu.rasi"
    
    handle_rofi
    return $?
}

change_bg() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"; shift
    local bg="${@?${texts[missingarg]:-"Missing argument bg"}}"
    IFS='|' read -d '' -r bgname bginfill bgcolor null <<< "${last_bg[${index}]}|"
    local display="${displays[index]// Unknown}"
    #send_notification "Attempt to set background: ${bg##*.}" "On display ${display#* }"
    case "${bg##*.}" in
        "jpg"|"jpeg"|"bmp"|"png"|"webp")
            killall mpvpaper
            # Use full display name i.e. ${display#* } to override default value in sway config
            last_bg[${index}]="${bg}|${bginfill}|${bgcolor}"
            ${SWAYMSG} output \"${display#* }\" bg \"${bg@Q}\" \"${bginfill}\" \"#${bgcolor}\" && mklink ${index}
        ;;
        "avi"|"mp4"|"webm"|"m3u")
            killall swaybg
            killall mpvpaper
            last_bg[${index}]="${bg}|${bginfill}|${bgcolor}"
            # Use port display name i.e. ${display%% *} as mpvpaper do not understand full display name
            ${SWAYMSG} exec -- ${MPVPAPER} ${display%% *} ${bg@Q} && mklink ${index}
        ;;
        \#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F])
            killall mpvpaper
            last_bg[${index}]="${texts[varunset]}|${bginfill}|${bg//#}"
            ${SWAYMSG} output \"${display#* }\" bg \"${bg}\" solid_color && mklink ${index}
    esac
    return $?
}

set_bg_image() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    #entries=""; actions=(); error_msgs=(); confirm=(); nocatch=();

    f="$(${ROFI} ${rofiargs// -dmenu} -show filebrowser -theme-str "@import \"./common/themes/vertical_menu.rasi\"" \
        -filebrowser-directories-first true \
        -filebrowser-directory "${WPSRCDIR/#~/$HOME}" \
        -filebrowser-filter-regex "^.*(?<!\.(jpg|png|bmp|jpeg|webp))$" \
        -filebrowser-command "echo -en " \
        -filebrowser-fallback-icon "image-x-generic" \
    )"
    #declare -a bgs
    #IFS=$NF read -d '' -a bgs <<< "$(${FIND} ${WPSRCDIR/#~/$HOME} -type f \
    #    -name \*\.jpg -o -name \*\.jpeg -o -name \*\.bmp -o -name \*\.png -o -name \*\.webp)"
    #for f in "${bgs[@]}"; do
    #    current="$([[ " ${f} " =~ " ${last_bg[$index]%%|*} " ]] && echo true || echo false )"
    #    entries+="$(write_menuentry "${f##*/}" "${current}" "${f}")"
        # Use full display name i.e. ${display#* } to override default value in sway config
    #    actions+=("change_bg ${index} ${f}")
    #    error_msgs+=( "${texts[cantset]} ${texts[display]} ${texts[image]} ${texts[background]}" )
    #done
    #header="${texts[availiable]^} ${texts[display]} ${texts[backgrounds]}"
    #theme="./common/themes/vertical_menu.rasi"
    #handle_rofi
    if [ -a "${f}" ]; then 
        change_bg ${index} "${f}"
    else
        send_notification "${texts[cant]^} ${texts[open]} ${texts[file]} ${f}"
    fi
    return $?
}

set_bg_video() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    #entries=""; actions=(); error_msgs=(); confirm=(); nocatch=();
    #declare -a bgs
    #IFS=$NF read -d '' -a bgs <<< "$(${FIND} ${WPSRCDIR/#~/$HOME} -type f \
    #    -name \*\.wmv -o -name \*\.mpeg -o -name \*\.mp4 -o -name \*\.webm -o -name \*\.avi)"
    #for f in "${bgs[@]}"; do
    #    current="$([[ " ${f} " =~ " ${last_bg[$index]%% *} " ]] && echo true || echo false )"
    #    entries+="$(write_menuentry "${f##*/}" "${current}" "${icons[videofile]}")"
    #    actions+=( "change_bg ${index} ${f}" )
    #    error_msgs+=( "${texts[cantset]} ${texts[display]} ${texts[video]} ${texts[background]}" )
    #done
    #header="${texts[availiable]^} ${texts[display]} ${texts[video]} ${texts[backgrounds]}"
    #theme="./common/themes/vertical_menu.rasi"
    #handle_rofi

    f="$(${ROFI} ${rofiargs// -dmenu} -show filebrowser -theme-str "@import \"./common/themes/vertical_menu.rasi\"" \
        -filebrowser-directories-first true \
        -filebrowser-directory "${WPSRCDIR/#~/$HOME}" \
        -filebrowser-filter-regex "^.*(?<!\.(avi|mp4|mpeg|ts|webm|wmv|m3u))$" \
        -filebrowser-command "echo -en " \
        -filebrowser-fallback-icon "video-x-generic" \
    )"
    
    if [ -a "${f}" ]; then 
        change_bg ${index} "${f}"
    else
        send_notification "${texts[cant]^} ${texts[open]} ${texts[file]} ${f}"
    fi
    return $?
}

set_bg_solid_color(){
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    entries="";
    declare -a colors
    colors=("#990000" "#009900" "#000099" "#000000" "#999999")
    for f in "${colors[@]}"; do
        current="$([[ " ${f} " =~ " ${last_bg[${index}]%%|*} " ]] && echo true || echo false )"
        entries+="$(write_menuentry "${f}" \
            "change_bg ${index} ${f}" \
            "<span background=\"${f}\">\U3000</span>" "${current}" "true" "false" "false" \
            "${texts[cantset]} ${texts[display]} ${texts[solidcolor]} ${texts[background]}" \
        )"
    done
    header="${texts[availiable]^} ${texts[display]} ${texts[colors]}"
    theme="./common/themes/vertical_menu.rasi"
    handle_rofi
    return $?
}

is_video(){
    local file="${@?${texts[missingarg]:-"Missing argument file"}}"
    [[ " wmv mpeg mp4 webm avi vob ts mkv m3u " =~ " ${file##*.} " ]] && echo true || echo false
}

is_image(){
    local file="${@?${texts[missingarg]:-"Missing argument file"}}"
    [[ " jpg jpeg bmp png webp tiff " =~ " ${file##*.} " ]] && echo true || echo false
}

is_solid(){
    local file="${@?${texts[missingarg]:-"Missing argument file"}}"
    [[ "${file}" == "${texts[varunset]}" ]] && echo true || echo false
}

set_bg_infill() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local enabled="false"
    IFS='|' read -r -d '\0' bgname bginfill bgcolor <<< "${last_bg[${index}]}"
    #send_notification "bg: ${last_bg[$index]} name: ${bgname} infill: ${bginfill} color: ${bgcolor}"
    entries="";    
    declare -a hints
    local infills=( "fill" "stretch" "center" "tile" )
    for i in "${!infills[@]}"; do
        enabled=$([[ "${bginfill}" == "${infills[i]}" ]] && echo true || echo false )
        entries+="$(write_menuentry "${texts[${infills[i]}]^}" \
            "change_infill ${index} ${infills[i]}" \
            "${icons[display${infills[i]}]}" "${enabled}" "true" "false" "false" \
            "${texts[cantset]} ${texts[display]} ${texts[background]} ${texts[infills]}" \
        )"
    done
    header="${texts[availiable]} ${texts[options]} ${texts[infills]}"
    theme="./common/themes/vertical_menu.rasi"
    
    handle_rofi
    return $?
}

change_infill() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"; shift
    local infill="${@?${texts[missingarg]:-"Missing argument infill"}}"
    local display="${displays[${index}]// Unknown}"
    #send_notification "Attempt to set infill: ${infill}" "On display ${display#* } bg: ${last_bg[$index]##*|}"
    # Use full display name i.e. ${display#* } to override default value in sway config
    last_bg[${index}]="${last_bg[$index]%%|*}|${infill}|${last_bg[$index]##*|}"
    ${SWAYMSG} output \"${display#* }\" bg \"${last_bg[$index]%%|*}\" \"${infill}\" \"#${last_bg[$index]##*|}\" && mklink ${index}

    return $?
}

is_config_included() {
    local config_path="${@?${texts[missingarg]:-"Missing argument config path"}}"
    local display="${displays[${index}]// Unknown}"
    local config_name="urd-sway-display-${display#* }"
    ${GREP} -q "^include ${config_path}/'${config_name##*/}'" "${config_path/\~/${HOME}}/config" && echo true || echo false
}

is_saved() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"; shift
    local display="${displays[${index}]// Unknown}"
    local config_path="~/.config/sway"
    local config_name="${config_path/\~/${HOME}}/urd-sway-display-${display#* }"

    local saved_mode=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*mode \(.*Hz\)$|\1|p" "${config_name}")
    local saved_bg=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*bg \(.*\)$|\1|p" "${config_name}")
    local saved_position=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*position \(.*\)$|\1|p" "${config_name}")
    local saved_scale=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*scale \(.*\)$|\1|p" "${config_name}")
    local saved_transform=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*transform \(.*\)$|\1|p" "${config_name}")
    local saved_subpixel=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*subpixel \(.*\)$|\1|p" "${config_name}")
    local saved_adaptive_sync=$(${SED} -ne "/output \"${display#* }\" {/,/}/s|^.*adaptive_sync \(.*\)$|\1|p" "${config_name}")

    if \
        [[ "${saved_bg//#/}" == "${last_bg[$index]//|/ }" ]] &&\
        [[ "${saved_mode}" == "${curr_modes[$index]:0:-3}.${curr_modes[$index]: -3}Hz" ]] &&\
        [[ "${saved_position}" == "${positions[$index]//,/}" ]] &&\
        [[ "${saved_scale}" == "${scales[$index]}" ]] &&\
        [[ "${saved_transform}" == "${transforms[$index]}" ]] &&\
        [[ "${saved_subpixel}" == "${hintings[$index]}" ]] &&\
        [[ "${saved_adaptive_sync}" == "${power[${adsyncs[$index]}]}" ]] &&\
        [[ "$(is_config_included "${config_path}")" == "true" ]]; then 
        echo true
    else
        echo false
    fi 
}

save_settings() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"; shift
    local display="${displays[${index}]// Unknown}"
    #send_notification "Attempt to save settings: ${display}" "On display ${display#* } bg: ${last_bg[$index]##*|}"
    # Use full display name i.e. ${display#* } to override default value in sway config
    IFS='|' read -r -d '\0' bgname bginfill bgcolor null <<< "${last_bg[${index}]}|"
    
    local config_path="~/.config/sway"
    local config_name="${config_path/\~/${HOME}}/urd-sway-display-${display#* }"
    #local config_included="$(${GREP} -q "^include ${config_path}/'${config_name##*/}'" "${config_path\~/${HOME}}/config" && echo true || echo false)"
    $(is_config_included "${config_path}") || echo -e "include ${config_path}/'${config_name##*/}'" >> "${config_path/\~/${HOME}}/config" || send_notification "${texts[failed]} ${texts[write]} ${config_path/\~/${HOME}}/config"
    
    echo -e "output \"${display#* }\" {" > "${config_name}"
    echo -e "    mode ${curr_modes[$index]:0:-3}.${curr_modes[$index]: -3}Hz" >> "${config_name}"
    echo -e "    bg ${bgname} ${bginfill} #${bgcolor}" >> "${config_name}"
    echo -e "    position ${positions[$index]//,/}" >> "${config_name}"
    echo -e "    scale ${scales[$index]}" >> "${config_name}"
    echo -e "    transform ${transforms[$index]}" >> "${config_name}"
    echo -e "    subpixel ${hintings[$index]}" >> "${config_name}"
    echo -e "    adaptive_sync ${power[${adsyncs[$index]}]}" >> "${config_name}"
    echo -e "}" >> "${config_name}"

    return $?
}

set_backgrounds() {
    local index="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[index]// Unknown}"
    local infill="$(cut -d'|' -f 2 <<< "${last_bg[${index}]}")"
    entries="";
    #send_notification "infill: ${infill} bg: ${last_bg[${index}]%%|*}"

    entries+="$(write_menuentry "${texts[infills]^}: ${texts[${infill}]^}" \
        "set_bg_infill ${i}" "${icons[displayinfill]}" "false" "true" \
    )"

    entries+="$(write_menuentry "${texts[solidcolor]^}" "set_bg_solid_color ${i}" \
        "<span background=\"#${last_bg[$index]##*|}\">\U3000</span>" "$(is_solid ${last_bg[${index}]%%|*})" "true" \
    )"

    entries+="$(write_menuentry "${texts[image]^}" "set_bg_image ${i}" \
        "${icons[imagefile]}" "$(is_image ${last_bg[${index}]%%|*})" "true" \
    )"

    entries+="$(write_menuentry "${texts[video]^}" "set_bg_video ${i}" \
        "${icons[videofile]}" "$(is_video ${last_bg[${index}]%%|*})" "true" \
    )"

    header="${texts[availiable]} ${texts[display]} ${texts[backgrounds]}"
    theme="./common/themes/vertical_menu.rasi"
    
    handle_rofi
    return $?
}

set_display() {
    local i="${1?${texts[missingarg]:-"Missing argument index"}}"
    local display="${displays[i]}"
    entries="";
    
    entries+="$(write_menuentry "${texts[${switch[${enabled[$i]}]}]^}" \
        "confirm ${SWAYMSG} output \"${display#* }\" toggle" \
        "${icons[power]}" "${enabled[$i]}" "true" "false" "false" \
        "${texts[cantset]} ${texts[displayactive]}" \
    )"
    
    if ${enabled[$i]}; then
    entries+="$(write_menuentry "${texts[displaymode]^}: ${curr_modes[i]:0:-3},${curr_modes[$i]: -3}" \
        "set_mode ${i}" "${icons[displaymode]}" "false" "true" \
    )"

    entries+="$(write_menuentry "${texts[displayposition]^}: ${texts[top]}: ${positions[$i]%%,*}, ${texts[left]}: ${positions[$i]##*, }" \
        "set_position ${i}" "${icons[displayposition]}" "false" "true" \
    )"
    
    entries+="$(write_menuentry "${texts[displayscale]^}: ${scales[$i]}" \
        "set_scale ${i}" "${icons[search]}" "false" "true" \
    )"
    
    entries+="$(write_menuentry "${texts[displaytransform]^}: ${texts[displaytransform_${transforms[$i]}]}" \
        "set_transform ${i}" \
        "${icons[displaytransform]}" "${default_transform[${transforms[$i]}]}" "true" \ 
    )"
    
    entries+="$(write_menuentry "${texts[adaptive_sync]^}: ${texts[${switch[${adsyncs[$i]}]}]}" \
        "${SWAYMSG} output \"${display#* }\" adaptive_sync ${switch[${adsyncs[$i]}]}" \
        "${icons[displaysync]}" "${bool[${adsyncs[$i]}]}" "true" "false" "false" \
        "${texts[cantset]} ${texts[adaptive_sync]}" \
    )"

    entries+="$(write_menuentry "${texts[subpixel_hinting]^}: ${texts[${hintings[$i]}]}" \
        "set_hinting ${i}" "${icons[displayhinting]}" "false" "true" \
    )"
    
    #entries+="$(write_menuentry "${texts[render_bit_depth]^}: ${hdrs[i]}" \
        #${SWAYMSG} output ${displays[i]%% *} render_bit_depth ${hdr[${hdrs[i]}]}" \
        #"${icons[displayhdr]}" "false" "true" "false" "false" \
        #"${texts[cantset]} ${texts[render_bit_depth]}" \
    #)"
    
    entries+="$(write_menuentry "${texts[backgrounds]^}" \
        "set_backgrounds ${i}" \
        "${icons[displaybg]}" "$([[ "${last_bg[${i}]%%|*}" == "${texts[varunset]}" ]] && echo false || echo true)" "true" \
    )"

    entries+="$(write_menuentry "${texts[save]^} ${texts[settings]}" \
        "save_settings ${i}" "${icons[save]}" "$(is_saved ${i})" "true" \
    )"
    fi

    header="${texts[availiable]} ${texts[options]} ${display}"
    theme="./common/themes/vertical_menu.rasi"
    
    handle_rofi
    return $?
}

declare -a last_bg

outputs="$(${SWAYMSG} -r -t get_outputs)"
IFS=$NF read -d '\0' -r -a displays <<< "$(${JQ} '.[] | [.name, .make, .model, .serial] | join(" ")' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a curr_modes <<< "$(${JQ} '.[] | .current_mode | [.width, "x" ,.height, "@", .refresh] | join("")' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a positions <<< "$(${JQ} '.[] | .rect | [.x, .y] | join(", ")' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a scales <<< "$(${JQ} '.[] | .scale' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a transforms <<< "$(${JQ} '.[] | .transform' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a adsyncs <<< "$(${JQ} '.[] | .adaptive_sync_status' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a hintings <<< "$(${JQ} '.[] | .subpixel_hinting' <<< ${outputs})"
IFS=$NF read -d '\0' -r -a enabled <<< "$(${JQ} '.[] | .active' <<< ${outputs})"
#IFS=$NF read -d '\0' -a hdrs <<< not implemented yet <<< ${outputs})"

[ ${#displays[@]} -eq 0 ] && die -1 "${texts[nodisplays]:-"No displays found"}"

for i in "${!displays[@]}"; do
    link_name="$(${FIND} "${HOME}/.local/state" -type l -name "lastbg_${displays[i]#* }_*" | tail -n1 )"
    link_name="${link_name:-"${HOME}/.local/state/lastbg_${displays[i]#* }_tile_111130"}"
    color="$(cut -d'_' -f 4 <<< "${link_name}")"
    infill="$(cut -d'_' -f 3 <<< "${link_name}")"
    file_name="$(readlink -q -n "${link_name}" 2>/dev/null || echo -e "${texts[varunset]}")|${infill}|${color}"
    last_bg+=( "${file_name/${HOME}\//\~/}" )
    #warn "link: ${link_name} bg: ${last_bg[i]} infill: ${infill} color: ${color}"
    entries+="$(write_menuentry "${displays[i]}" \
        "set_display ${i}" \
        "${icons[${displays[i]%%-*}]}" "${enabled[i]}" \
    )"
done

handle_rofi

