#!/usr/bin/env bash
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
CAL="cal -1 -m -v --color=never"
RDEPS+="${CAL},"
source "./common/definitions"
prog="${0##*/}"
args="$*"
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
handle_common_opts "$@"
rofiargs="${default_rofiargs/-dmenu/-use-hot-keys} -format p"
#rofiargs="${default_rofiargs} -use-hot-keys -format p"
theme="./common/themes/month.rasi"

while [ "$#" -ge 1 ]; do
    case "${1?${texts[missingarg]:-Missing argument} script options}" in
        --data=*)
						ROFI_DATA="${1#--data=*}"
						shift
						;;
				--) 
						shift; break ;;
 				*)
	      		break
	      		;;
    esac
done

new_month() {
		ROFI_DATA="${ROFI_DATA:-$(date +'%-Y-%-m')}"
	  IFS=- read year month <<< "$ROFI_DATA"
	  day="$(date +%-d)"
		cal=$(${CAL} ${month} ${year})
		header="$(${SED} -n 's/^ *//g;s/ *$//g;s/2\([0-9][0-9]\+\)/ऊ1\1/p' <<< "${cal}")" # Julian calendar year fix
		entries="$(echo -n "${cal}" | ${SED} '1d' | ${SED} 's/./\n/3;P;D' | ${SED} 's/\([^0-9][^0-9]\)$/\1\\x00nonselectable\\x1ftrue\\x1furgent\\x1ftrue/g' )"
		parsed_entries="$(sed -z 's/\\n/\n/g' <<< "${entries}")"
		if [[ "$year-$month" = "$(date +'%-Y-%-m')" ]]; then
		  	active="$(echo -n "${parsed_entries}" | ${SED} -n "s/[[:space:]]//g;/^${day}$/=" | ${SED} -z 's/\([0-9]*\)\n/echo -n $((\1-1));/ge')"
		else
		  	active="255"
		fi
}

new_month
handle_rofi

case ${rofi_ret:-${ROFI_RETV}} in
		10) # rofi kb-custom-1: go to prev month
				year=$(( month-1 < 1 ? year-1 : year ))
				month=$(( month-1 < 1 ? 12 : month-1 ))
		;;
		11) # rofi kb-custom-2: go to next month
				year=$(( month+1 > 12 ? year+1 : year ))
				month=$(( month+1 > 12 ? 1 : month+1 ))
		;;
		12) # rofi kb-custom-3: go to prev year
				year=$(( year-1 ))
		;;
		13) # rofi kb-custom-4: go to next year
				year=$(( year+1 ))
		;;
		14) # rofi kb-custom-5: go to current month
				IFS=- read -r year month <<< $(date +'%-Y-%-m')
		;;
esac

if ${force_dmenu} ; then
		case ${rofi_ret} in
		0)  # selected
			  selected_date="$(date -d "${year}-${month}-${chosen_row}" 2>/dev/null)"
				wl-copy -p "${selected_date}"
				send_notification "${texts[copied]^}: ${selected_date}"
		;;
		1)  # Cancelled by user
    		die 0 "${texts[canceled]:-"Cancelled..."}"
		;;
		1[0-4])
				./${prog} ${args//--data=*/} --data="$year-$month"
		;;
		esac
else
		case ${ROFI_RETV} in
		1)  # set date
				selected_date="$(date -d "${year}-${month}-${args}" 2>/dev/null)"
				wl-copy -p "${selected_date}" && send_notification "${texts[copied]^}: ${selected_date}" || die
		;;
		1[0-4])
				ROFI_DATA="$year-$month"
				new_month
				write_script_entries
		;;
		esac
fi

