#!/usr/bin/env sh
#
# Rofi powered menu to prompt a password.
# Uses: rofi
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog="${prog//-/_}"
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_common_opts "$@"
rofiargs="${default_rofiargs} -no-custom -format p "

header="${texts[header_screen-keyboard]:-Screen Keyboard}"
theme="./common/themes/vertical_querty_40.rasi"

entries="1\n2\n3\n4\n5\n6\n7\n8\n9\n0\nq\nw\ne\nr\nt\ny\nu\ni\no\np\na\ns\nd\nf\ng\nh\nj\nk\nl\net\nsh\nz\nx\nc\nv\nb\nn\nm\nsp\nctrl"

#entries="$(echo -n "${entries}" | ${SED} 's/./\n/3;P;D' )"

handle_rofi
