#!/usr/bin/env bash
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
TIMEOUT=3
NMCLI="nmcli -w ${TIMEOUT} -c no -e no -t"
RDEPS="${NMCLI},"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"

# parse options
handle_common_opts "$@"
source "./common/langs/${default_lang}"

rofiargs="${default_rofiargs} -no-custom -format i "
default_themestr+="element-text { tab-stops: [6em]; } "
header="${texts[header_network_info]^}"
theme="./common/themes/vertical_menu.rasi"

show_netdev_info() {
    local device="${1?${texts[missingarg]:-Missing argument} device}"
    declare -a info 
    IFS=$NF read -r -d '' -a info <<< $(${NMCLI} dev show ${device})
    entries=""; actions=(); error_msgs=(); confirm=();
    for i in ${!info[@]}; do
        left_info=${info[i]%%:*}
        entries+="$(write_menuentry "${left_info:0:16}:\t${info[i]#*:}")"
        error_msgs+=( "${texts[cant]}^} ${texts[copy]}" )
    done
    header="${texts[header_networkdeviceinfo]:-Network device info} ${device}"
    theme="./common/themes/vertical_menu.rasi"
    default_themestr+="element-text { tab-stops: [9em]; } "
    default_themestr+="element-icon { enabled: false; } "
    default_themestr+="button-toggle { enabled: false; } "
    handle_rofi

    case ${rofi_ret} in
    0)  # copy selected row value
		wl-copy -p "${info[${chosen_row}]#*:}" 2>/dev/null
		send_notification "${texts[copied]:-Copied}: ${info[${chosen_row}]#*:}"
    ;;
    1)  # Cancelled by user
        die 0 "${texts[canceled]:-"Cancelled..."}"
    esac
}

declare -a netdev
IFS=$NF read -r -d '' -a netdev <<< $(${NMCLI} dev)
[[ ${#netdev[@]} -eq 0 ]] && die -1 "${texts[nonetworkdevices]}"
#warn "${netdev[@]}"

for i in ${!netdev[@]}; do
    IFS=':' read -r -d '' name type connected connection <<< "${netdev[i]}"
    #warn "${name} ${type} ${connection//[$'\t\r\n']} ${connected}"
    enabled="$([[ " ${connected} " =~ " connected " ]] && echo true || echo false)"
    entries+="$(write_menuentry "${type^}\t${name} ${connection//[$'\t\r\n']}" "${enabled}" "${icons[${type%%-*}]:-""}")"
    actions+=( "show_netdev_info ${name}" )
    nocatch+=( true )
done

handle_rofi

