#!/usr/bin/env sh
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
WPCTL="/usr/bin/wpctl"
RDEPS+="${WPCTL},"
source "./common/definitions"
prog="${0##*/}"
args="$*"
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_script_opts "$@"
source "./common/langs/${default_lang}"
rofiargs="${default_rofiargs} -no-custom -format i "
header="${texts[header_pipewire_sink]}"
theme="./common/themes/vertical_menu.rasi"

declare -A act
act[select]="${WPCTL} set-default"
act[toggle]="${WPCTL} set-mute"

IFS=$NF read -d '' -a devices <<< "$(${WPCTL} status | ${SED} -n '/ ├─ Sinks:/,/ │  $/ {//! p}' | ${SED} -n 's/^ │  \(.*\)$/\1/p' )"
[ ${#devices[@]} -eq 0 ] && die 1 "${texts[noaudiosinks]:-"No audio device sinks"}"

for i in "${!devices[@]}"; do
    str="${devices[i]}"
    enabled="$( [[ "${str:0:1}" == "*" ]] && echo toggle || echo select )"
    volume="$(${SED} -n 's/.\+\[vol: [0-1]\.\([0-9]\)[0-9]\(.*\)\]/\1\2/p' <<< ${str})"
    ids="$(${SED} -n "s/^[* ]\+\([0-9]\+\).*$/\1/p" <<< ${str})"
    name="$(${SED} -n "s/^[* ]\+[0-9]\+\. \(.*\)\[.*$/\1/p" <<< ${str})"
    device="$(${WPCTL} inspect ${ids} | ${SED} -n 's/^ \+api\.alsa\.pcm\.id = \"\([A-Z]\+\).*\"/\1/p')"
    entries+="$(write_menuentry "${icons[vol${volume// }]} ${name}" "${bool[${enabled}]}" "${icons[${device}]}")\n"
    actions+=( "${act[${enabled}]} ${ids} ${enabled}" )
    error_msgs+=( "${texts[cant]:-"Can't"} ${texts[set]:-"set"} ${texts[audiosink]:-"audio sink"}" )
done

handle_rofi

