#!/usr/bin/env bash
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
LOCK="swaylock -f -c 000000"
LOGIND="loginctl --no-ask-password"
RDEPS="${LOCK},${LOGIND},"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [$texts[options]]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_common_opts "$@"
source "./common/langs/${default_lang}"  # sourcing default lang here is urgent for common optional argument -lang=xx_XX
rofiargs+=" -dmenu"

# All supported choices
all=(poweroff reboot suspend hibernate firmware logout lock)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")
#show=(poweroff reboot suspend logout lock) 

declare -A act
act[lock]="${LOCK}"
#act[lock]="${LOGIND} lock-session ${XDG_SESSION_ID-}"
act[logout]="confirm ${LOGIND} kill-user ${USER}"
act[suspend]="${LOGIND} suspend"
act[hibernate]="${LOGIND} hibernate"
act[reboot]="confirm ${LOGIND} reboot"
act[poweroff]="confirm ${LOGIND} poweroff"
act[firmware]="confirm ${LOGIND} --firmware-setup reboot"

for i in "${show[@]}"; do
    entries+="$(write_menuentry "${texts[${i}]^}" "${act[${i}]}" \
        "${icons[${i}]}" "false" "true" "false" "false" \
        "${texts[${i}]} ${texts[failed]}." \
    )"
done

header="${texts[header_logout_menu]^}"
theme="./common/themes/vertical_menu.rasi"
handle_rofi

