#!/usr/bin/env bash
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
UDISKSCTL="/usr/bin/udisksctl"
LSBLK="/bin/lsblk -n -l"
RDEPS+="${UDISKSCTL},${LSBLK}"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_common_opts "$@"
source "./common/langs/${default_lang}"
rofiargs="${default_rofiargs} -no-custom -format i "
default_themestr+="element-text { tab-stops: [8em, 12em]; } "
header="${texts[header_usbstor_mounter]}"
theme="./common/themes/vertical_menu.rasi"

is_mounted() {
    local device="${1?${texts[missingarg]:-Missing argument} device}"
    ${GREP} -q "$(readlink -f "${device}")" /proc/mounts 2>/dev/null && echo true || echo false
}

mount_all() {
    local device="${1?${texts[missingarg]:-Missing argument} device}"
    for part in ${device}-part?*; do 
        ${UDISKSCTL} mount -b ${part} --no-user-interaction
    done
}

unmount_all() {
    local device="${1?${texts[missingarg]:-Missing argument} device}"
    for part in ${device}-part?*; do 
        ${UDISKSCTL} unmount -b ${part} --no-user-interaction
    done
    ${UDISKSCTL} power-off -b ${device} && send_notification "${texts[usbpoweroff]}" || send_notification "${texts[cantusbpoweroff]}"
}

declare -a devices
IFS=$NF read -d \" -r -a devices <<< "$(${LS} /dev/disk/by-id/* | ${SED} -ne '/\(usb-.*-0\:[0-9]\+\)$/p' 2>/dev/null)"
[ ${#devices[@]} -eq 0 ] && die -1 "${texts[nousbblockdevice]}"

declare -A act
act=( [true]="unmount_all" [false]="mount_all" )

for i in "${!devices[@]}"; do
    name="$(${LSBLK} -d -o TRAN,VENDOR,MODEL,LABEL "${devices[i]}" 2>/dev/null | ${SED} 's/[[:space:]]\+/ /g;s/\(^[a-z]\+\)/\U\1/')"
    mounted=$(is_mounted "${devices[i]}")
    #warn "${devices[i]} mounted=$mounted"
    entries+="$(write_menuentry "${name}" "${mounted}" "${icons[USB]}" "true")\n"
    actions+=( "${act[${mounted}]} ${devices[i]}" )
    error_msgs+=( "${texts[cant]} ${texts["${act[${mounted}]}%%_*"]} ${texts[device]:-device}: ${devices[i]}" )
    IFS=$NF read -d \" -r -a partitions <<< "$(${LS} ${devices[i]}-part* 2>/dev/null)"
    for j in "${!partitions[@]}"; do
        label="$(${LSBLK} -o LABEL ${partitions[j]})"
        mounted=$(is_mounted "${partitions[$j]}")
        name="${label:0:16}\t$(${LSBLK} -o FSTYPE,SIZE "${partitions[j]}" | ${SED} 's/[[:space:]]\+/\t/g;s/</\&\#x003c;/')"
        entries+="$(write_menuentry "$(get_branch_icon "${#partitions[@]}" "$j") ${name}" "${mounted}" "${icons[partition]}")\n"
        actions+=( "${UDISKSCTL} ${act[${mounted}]%%_*} --no-user-interaction -b ${partitions[j]}" )
        error_msgs+=( "${texts[cant]} ${texts[${act[${mounted}]%%*_}]} ${texts[partition]:-partition}: ${partitions[j]})]}" )
    done
done

handle_rofi
