#!/usr/bin/env sh
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
LOCK="/usr/bin/swaylock -f -c 000000"
LOGIND="/bin/loginctl"
RDEPS+="${LOCK},${LOGIND},"
source "./common/definitions"
prog="${0##*/}"
args=$*
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [$texts[options]]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
# parse options
handle_script_opts "$@"
source "./common/langs/${default_lang}"

rofiargs="${default_rofiargs} -no-custom -format i "

# All supported choices
all=(poweroff reboot suspend hibernate logout lock)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")
#show=(poweroff reboot suspend logout lock) 

# By default, ask for confirmation for actions that are irreversible
confirmations=(reboot poweroff logout)

declare -A act
act[lock]="${LOCK}"
#act[lock]="${LOGIND} lock-session ${XDG_SESSION_ID-}"
act[logout]="${LOGIND} kill-user $USER"
act[suspend]="${LOGIND} suspend"
act[hibernate]="${LOGIND} hibernate"
act[reboot]="${LOGIND} reboot"
act[poweroff]="${LOGIND} poweroff"

for i in "${show[@]}"; do
    entries+="$(write_menuentry "${texts[${i}]^}" "false" "${icons[${i}]}" "true")\n"
    confirm+=( $( [[ "${confirmations[@]}" =~ "${i}" ]] && echo true || echo false) )
    actions+=( "${act[${i}]}" )
    error_msgs+=( "${texts[${i}]} ${texts[failed]:-failed}." )
done

header="${texts[header_logout_menu]}"
theme="./common/themes/vertical_menu.rasi"
handle_rofi

