#!/usr/bin/env bash
ORIGIN="$(readlink -q "${BASH_SOURCE[0]}" || echo -e "${BASH_SOURCE[0]}" )"
cd "${ORIGIN%/*}"
CAL="cal -1 -m -v --color=never"
RDEPS+="${CAL},"
source "./common/definitions"
prog="${0##*/}"
args="$*"
nprog=${prog//-/_}
usage="${texts[usage]}: ${prog} [${texts[options]}]

    ${texts[usage_${nprog##*urd_}]^}
    ${common_usage}
"
handle_common_opts "$@"
rofiargs="${rofiargs//-use-hot-keys -format p} -use-hot-keys -format p"
theme="./common/themes/month.rasi"

while [ "$#" -ge 1 ]; do
		case "${1?${texts[missingarg]:-Missing argument} script options}" in
				--data=*)
						ROFI_DATA="${1#--data=*}"
						shift
						;;
				--) 
						shift; break ;;
				*)
	      		break
	      		;;
    esac
done

handle_date() {
		local day="${1?${texts[missingarg]:-Missing argument} day}"
		local date="$(date -d "${year}-${month}-${day}" 2>/dev/null)"
		entries="$(write_menuentry "${texts[copy]^}" \
				"wl-copy -p ${date}" \
				"${icons[copy]}" "false" "true" "false" "false" \
				"${texts[cant]} ${texts[copy]} ${date}" \
		)"
		entries+="$(write_menuentry "${texts[set]^}" \
        "cron ${date}" \
        "${icons[reminder]}" "false" "true" "false" "false" \
        "${texts[cantset]} ${texts[reminder]} ${date}" \
    )"

		header="${date}"
		theme="./common/themes/vertical_menu.rasi"

    handle_rofi
    return $?
}

new_month() {
		ROFI_DATA="${ROFI_DATA:-$(date +'%-Y-%-m')}"
	  IFS=- read year month <<< "${ROFI_DATA}"
	  local day="$(date +%-d)"
		cal=$(${CAL} ${month} ${year})
		header="$(${SED} -n 's/^ *//g;s/ *$//g;s/2\([0-9][0-9]\+\)/ऊ1\1/p' <<< "${cal}")" # Julian calendar year fix
		entries="$(echo -n "${cal}" | ${SED} '1d' | ${SED} 's/./\n/3;P;D' | ${SED} 's/\([^0-9][^0-9]\)$/\1\\x00nonselectable\\x1ftrue\\x1furgent\\x1ftrue/g' )"
		parsed_entries="$(sed -z 's/\\n/\n/g' <<< "${entries}")"
		if [[ "$year-$month" == "$(date +'%-Y-%-m')" ]]; then
		  	active="$(echo -n "${parsed_entries}" | ${SED} -n "s/[[:space:]]//g;/^${day}$/=" | ${SED} -z 's/\([0-9]*\)\n/echo -n $((\1-1));/ge')"
		else
		  	active="255"
		fi
		entries="$(${SED} 's/\([0-9]\+\)$/if [[ "\1" == "${active}" ]]; then a=true; else a=false; fi; echo -n "handle_date \1\\x00display\\x1f\1\\x1fpermanent\\x1ftrue\\x1factive\\x1f${a}"/ge' <<< "${entries}")"
}

new_month
handle_rofi

case ${rofi_ret:-${ROFI_RETV}} in
		10) # rofi kb-custom-1: go to prev month
				year=$(( month-1 < 1 ? year-1 : year ))
				month=$(( month-1 < 1 ? 12 : month-1 ))
		;;
		11) # rofi kb-custom-2: go to next month
				year=$(( month+1 > 12 ? year+1 : year ))
				month=$(( month+1 > 12 ? 1 : month+1 ))
		;;
		12) # rofi kb-custom-3: go to prev year
				year=$(( year-1 ))
		;;
		13) # rofi kb-custom-4: go to next year
				year=$(( year+1 ))
		;;
		14) # rofi kb-custom-5: go to current month
				IFS=- read -r year month <<< $(date +'%-Y-%-m')
		;;
esac

if ${force_dmenu} ; then
		case ${ROFI_RETV} in
		1[0-4])
				exec ./${prog} ${args//--data=*/} --data="$year-$month"
		;;
		esac
else
		case ${ROFI_RETV} in
		1[0-4])
				ROFI_DATA="$year-$month"
				new_month
				write_script_entries
		;;
		esac
fi

